/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.customlinkedlist.CustomLinkedList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Random;
import java.util.stream.Stream;

public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) {

        var random = new Random();

        var stream = Stream.generate(() -> random.nextInt(10000))
                .limit(15);

        var customList = stream.reduce(
                new CustomLinkedList<>(),
                (list, element) -> {
                    list.add(element);
                    return list;
                },
                (list1, list2) -> {
                    list1.addAll(list2);
                    return list1;
                }
        );

        var log = customList.toString();
        LOGGER.info(log);
    }
}
