spring:
  application:
    name: crud-kuda-go

app:
  data-init:
    interval: 60
  thread-pool:
    size: 10
  scheduled:
    thread-pool:
      size: 10

external:
  api:
    kudago:
      base-url: "https://kudago.com/public-api/v1.4"
      timeout:
        connect: 5000
        read: 10000
