spring:
  application:
    name: crud-kuda-go
  jpa:
    hibernate:
      ddl-auto: none
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
    liquibase:
      change-log: classpath:migrations/db.changelog-master.yaml
server:
  port: 8081
external:
  api:
    kudago:
      base-url: "https://kudago.com/public-api/v1.4"
      timeout:
        connect: 5000
        read: 10000
