name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Run tests with coverage
        working-directory: crud-kuda-go
        run: ./gradlew test jacocoTestReport

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: crud-kuda-go/build/reports/jacoco/test/jacocoTestReport.xml

  build_and_publish:
    name: build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: [ tests ]
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        working-directory: crud-kuda-go
        run: ./gradlew clean build -x test

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FJ }}

      - name: Check if JAR file exists
        run: |
          if [ ! -f crud-kuda-go/build/libs/crud-kuda-go.jar ]; then
            echo "JAR file not found! Check if the build step created the file."
            exit 1
          fi

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/prismgentem/fintech:latest -f crud-kuda-go/Dockerfile .

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/prismgentem/fintech:latest
